**First Dataset**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
path="/content/drive/MyDrive/Data-cleaning-for-beginners-using-pandas.csv"
data=pd.read_csv(path)

In [ ]:
data.head(20)

    Index   Age      Salary  Rating       Location  Established Easy_Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3  64.0   $44k-$99k     4.4       India In         1988         -1
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009         -1
12     12   NaN   $44k-$99k     0.0       India,In         1999         -1
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16     16  19.0   $19k-$40k     4.5       India,In         1984         -1
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy_Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
###For Easy_Apply
data.rename(columns = {'Easy Apply':'Easy_Apply'}, inplace = True)
data["Easy_Apply"]=data["Easy_Apply"].str.replace("-1","False")
data

    Index   Age      Salary  Rating       Location  Established Easy_Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1      False
3       3  64.0   $44k-$99k     4.4       India In         1988      False
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002      False
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1      False
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1      False
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1      False
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009      False
12     12   NaN   $44k-$99k     0.0       India,In         1999      False
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999      False
16     16  19.0   $19k-$40k     4.5       India,In         1984      False
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21  35.0   $44k-$99k     5.0    New York,Ny         1946      False
22     22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24  13.0   $44k-$99k    -1.0    New York,Ny         1987      False
25     25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0   $44k-$99k     5.4       India,In         1935      False
28     28   NaN   $39k-$88k     3.4  Australia Aus         1932      False

In [ ]:
####For Age columnn
avg_age=data['Age'].mean()
avg_age
data.Age.fillna(avg_age)
data['Age']=data.Age.fillna(avg_age)
data['Age']=data.Age.astype(int)
data

    Index  Age      Salary  Rating       Location  Established Easy_Apply
0       0   44   $44k-$99k     5.4       India,In         1999       TRUE
1       1   66   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   39   $77k-$89k    -1.0    New York,Ny           -1      False
3       3   64   $44k-$99k     4.4       India In         1988      False
4       4   25   $44k-$99k     6.4  Australia Aus         2002      False
5       5   44   $77k-$89k     1.4       India,In         1999       TRUE
6       6   21   $44k-$99k     0.0    New York,Ny           -1      False
7       7   44   $44k-$99k    -1.0  Australia Aus           -1      False
8       8   35   $44k-$99k     5.4    New York,Ny           -1      False
9       9   22   $44k-$99k     7.7       India,In           -1       TRUE
10     10   55   $10k-$49k     5.4       India,In         2008       TRUE
11     11   44   $10k-$49k     6.7       India,In         2009      False
12     12   39   $44k-$99k     0.0       India,In         1999      False
13     13   25   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14   66   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15   44  $88k-$101k     3.0  Australia Aus         1999      False
16     16   19   $19k-$40k     4.5       India,In         1984      False
17     17   39   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18   35   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19   32   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   39   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21   35   $44k-$99k     5.0    New York,Ny         1946      False
22     22   19   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   39   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24   13   $44k-$99k    -1.0    New York,Ny         1987      False
25     25   55   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   39   $55k-$66k     NaN       India,In         1934       TRUE
27     27   52   $44k-$99k     5.4       India,In         1935      False
28     28   39   $39k-$88k     3.4  Australia Aus         1932      False

In [ ]:
### For Salary column
data['Salary']=data.Salary.str.replace("$"," ")
data['Salary']=data.Salary.str.replace("k","000")
data[['Min_Salary', 'Max_Salary']] = data['Salary'].str.split('-', expand=True)
data = data.drop(columns=['Salary'])
data

<ipython-input-30-14844cbd8648>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Salary']=data.Salary.str.replace("$"," ")

,Index,Age,Rating,Location,Established,Easy_Apply,Min_Salary,Max_Salary
0,0,44,5.4,"India,In",1999,TRUE,44000,99000
1,1,66,3.5,"New York,Ny",2002,TRUE,55000,66000
2,2,39,-1.0,"New York,Ny",-1,False,77000,89000
3,3,64,4.4,India In,1988,False,44000,99000
4,4,25,6.4,Australia Aus,2002,False,44000,99000
5,5,44,1.4,"India,In",1999,TRUE,77000,89000
6,6,21,0.0,"New York,Ny",-1,False,44000,99000
7,7,44,-1.0,Australia Aus,-1,False,44000,99000
8,8,35,5.4,"New York,Ny",-1,False,44000,99000
9,9,22,7.7,"India,In",-1,TRUE,44000,99000
10,10,55,5.4,"India,In",2008,TRUE,10000,49000
11,11,44,6.7,"India,In",2009,False,10000,49000
12,12,39,0.0,"India,In",1999,False,44000,99000
13,13,25,-1.0,Australia Aus,2019,TRUE,44000,99000
14,14,66,4.0,Australia Aus,2020,TRUE,44000,99000
15,15,44,3.0,Australia Aus,1999,False,88000,101000
16,16,19,4.5,"India,In",1984,False,19000,40000
17,17,39,5.3,"New York,Ny",1943,TRUE,44000,99000
18,18,35,6.7,"New York,Ny",1954,TRUE,44000,99000
19,19,32,3.3,"New York,Ny",1955,TRUE,44000,99000
20,20,39,5.7,"New York,Ny",1944,TRUE,44000,99000
21,21,35,5.0,"New York,Ny",1946,False,44000,99000
22,22,19,7.8,"New York,Ny",1988,TRUE,55000,66000
23,23,39,2.4,"New York,Ny",1999,TRUE,44000,99000
24,24,13,-1.0,"New York,Ny",1987,False,44000,99000
25,25,55,0.0,Australia Aus,1980,TRUE,44000,99000
26,26,39,NaN,"India,In",1934,TRUE,55000,66000
27,27,52,5.4,"India,In",1935,False,44000,99000
28,28,39,3.4,Australia Aus,1932,False,39000,88000

In [ ]:
### For Rating Column
data["Rating"] = data["Rating"].replace(-1.0, np.nan)
avg_rating=data['Rating'].mean()
data['Rating']=data.Rating.fillna(avg_rating)
data['Rating']=data.Rating.round(decimals=1)
data

,Index,Age,Rating,Location,Established,Easy_Apply,Min_Salary,Max_Salary
0,0,44,5.4,"India,In",1999,TRUE,44000,99000
1,1,66,3.5,"New York,Ny",2002,TRUE,55000,66000
2,2,39,4.3,"New York,Ny",-1,False,77000,89000
3,3,64,4.4,India In,1988,False,44000,99000
4,4,25,6.4,Australia Aus,2002,False,44000,99000
5,5,44,1.4,"India,In",1999,TRUE,77000,89000
6,6,21,0.0,"New York,Ny",-1,False,44000,99000
7,7,44,4.3,Australia Aus,-1,False,44000,99000
8,8,35,5.4,"New York,Ny",-1,False,44000,99000
9,9,22,7.7,"India,In",-1,TRUE,44000,99000
10,10,55,5.4,"India,In",2008,TRUE,10000,49000
11,11,44,6.7,"India,In",2009,False,10000,49000
12,12,39,0.0,"India,In",1999,False,44000,99000
13,13,25,4.3,Australia Aus,2019,TRUE,44000,99000
14,14,66,4.0,Australia Aus,2020,TRUE,44000,99000
15,15,44,3.0,Australia Aus,1999,False,88000,101000
16,16,19,4.5,"India,In",1984,False,19000,40000
17,17,39,5.3,"New York,Ny",1943,TRUE,44000,99000
18,18,35,6.7,"New York,Ny",1954,TRUE,44000,99000
19,19,32,3.3,"New York,Ny",1955,TRUE,44000,99000
20,20,39,5.7,"New York,Ny",1944,TRUE,44000,99000
21,21,35,5.0,"New York,Ny",1946,False,44000,99000
22,22,19,7.8,"New York,Ny",1988,TRUE,55000,66000
23,23,39,2.4,"New York,Ny",1999,TRUE,44000,99000
24,24,13,4.3,"New York,Ny",1987,False,44000,99000
25,25,55,0.0,Australia Aus,1980,TRUE,44000,99000
26,26,39,4.3,"India,In",1934,TRUE,55000,66000
27,27,52,5.4,"India,In",1935,False,44000,99000
28,28,39,3.4,Australia Aus,1932,False,39000,88000

In [ ]:
###For Location Column
data[['Location','Country_initials']] = data['Location'].str.split(',', expand=True)
data['Location']=data.Location.str.replace(" Aus"," ")
data['Country_initials']=data.Country_initials.str.replace("None","Aus")
data['Country_initials']=data.Country_initials.fillna('Aus')
data

,Index,Age,Rating,Location,Established,Easy_Apply,Min_Salary,Max_Salary,Country_initials
0,0,44,5.4,India,1999,TRUE,44000,99000,In
1,1,66,3.5,New York,2002,TRUE,55000,66000,Ny
2,2,39,4.3,New York,-1,False,77000,89000,Ny
3,3,64,4.4,India In,1988,False,44000,99000,Aus
4,4,25,6.4,Australia,2002,False,44000,99000,Aus
5,5,44,1.4,India,1999,TRUE,77000,89000,In
6,6,21,0.0,New York,-1,False,44000,99000,Ny
7,7,44,4.3,Australia,-1,False,44000,99000,Aus
8,8,35,5.4,New York,-1,False,44000,99000,Ny
9,9,22,7.7,India,-1,TRUE,44000,99000,In
10,10,55,5.4,India,2008,TRUE,10000,49000,In
11,11,44,6.7,India,2009,False,10000,49000,In
12,12,39,0.0,India,1999,False,44000,99000,In
13,13,25,4.3,Australia,2019,TRUE,44000,99000,Aus
14,14,66,4.0,Australia,2020,TRUE,44000,99000,Aus
15,15,44,3.0,Australia,1999,False,88000,101000,Aus
16,16,19,4.5,India,1984,False,19000,40000,In
17,17,39,5.3,New York,1943,TRUE,44000,99000,Ny
18,18,35,6.7,New York,1954,TRUE,44000,99000,Ny
19,19,32,3.3,New York,1955,TRUE,44000,99000,Ny
20,20,39,5.7,New York,1944,TRUE,44000,99000,Ny
21,21,35,5.0,New York,1946,False,44000,99000,Ny
22,22,19,7.8,New York,1988,TRUE,55000,66000,Ny
23,23,39,2.4,New York,1999,TRUE,44000,99000,Ny
24,24,13,4.3,New York,1987,False,44000,99000,Ny
25,25,55,0.0,Australia,1980,TRUE,44000,99000,Aus
26,26,39,4.3,India,1934,TRUE,55000,66000,In
27,27,52,5.4,India,1935,False,44000,99000,In
28,28,39,3.4,Australia,1932,False,39000,88000,Aus

In [ ]:
###For Established Column
data["Established"]=data["Established"].astype(str)
data["Established"] = data["Established"].str.replace('-1','Unknown')
data

,Index,Age,Rating,Location,Established,Easy_Apply,Min_Salary,Max_Salary,Country_initials
0,0,44,5.4,India,1999,TRUE,44000,99000,In
1,1,66,3.5,New York,2002,TRUE,55000,66000,Ny
2,2,39,4.3,New York,Unknown,False,77000,89000,Ny
3,3,64,4.4,India In,1988,False,44000,99000,Aus
4,4,25,6.4,Australia,2002,False,44000,99000,Aus
5,5,44,1.4,India,1999,TRUE,77000,89000,In
6,6,21,0.0,New York,Unknown,False,44000,99000,Ny
7,7,44,4.3,Australia,Unknown,False,44000,99000,Aus
8,8,35,5.4,New York,Unknown,False,44000,99000,Ny
9,9,22,7.7,India,Unknown,TRUE,44000,99000,In
10,10,55,5.4,India,2008,TRUE,10000,49000,In
11,11,44,6.7,India,2009,False,10000,49000,In
12,12,39,0.0,India,1999,False,44000,99000,In
13,13,25,4.3,Australia,2019,TRUE,44000,99000,Aus
14,14,66,4.0,Australia,2020,TRUE,44000,99000,Aus
15,15,44,3.0,Australia,1999,False,88000,101000,Aus
16,16,19,4.5,India,1984,False,19000,40000,In
17,17,39,5.3,New York,1943,TRUE,44000,99000,Ny
18,18,35,6.7,New York,1954,TRUE,44000,99000,Ny
19,19,32,3.3,New York,1955,TRUE,44000,99000,Ny
20,20,39,5.7,New York,1944,TRUE,44000,99000,Ny
21,21,35,5.0,New York,1946,False,44000,99000,Ny
22,22,19,7.8,New York,1988,TRUE,55000,66000,Ny
23,23,39,2.4,New York,1999,TRUE,44000,99000,Ny
24,24,13,4.3,New York,1987,False,44000,99000,Ny
25,25,55,0.0,Australia,1980,TRUE,44000,99000,Aus
26,26,39,4.3,India,1934,TRUE,55000,66000,In
27,27,52,5.4,India,1935,False,44000,99000,In
28,28,39,3.4,Australia,1932,False,39000,88000,Aus

In [ ]:
new_columns=['Age','Rating','Location','Country_initials','Established','Easy_Apply','Min_Salary','Max_Salary']
data=data[new_columns]
data

,Age,Rating,Location,Country_initials,Established,Easy_Apply,Min_Salary,Max_Salary
0,44,5.4,India,In,1999,TRUE,44000,99000
1,66,3.5,New York,Ny,2002,TRUE,55000,66000
2,39,4.3,New York,Ny,Unknown,False,77000,89000
3,64,4.4,India In,Aus,1988,False,44000,99000
4,25,6.4,Australia,Aus,2002,False,44000,99000
5,44,1.4,India,In,1999,TRUE,77000,89000
6,21,0.0,New York,Ny,Unknown,False,44000,99000
7,44,4.3,Australia,Aus,Unknown,False,44000,99000
8,35,5.4,New York,Ny,Unknown,False,44000,99000
9,22,7.7,India,In,Unknown,TRUE,44000,99000
10,55,5.4,India,In,2008,TRUE,10000,49000
11,44,6.7,India,In,2009,False,10000,49000
12,39,0.0,India,In,1999,False,44000,99000
13,25,4.3,Australia,Aus,2019,TRUE,44000,99000
14,66,4.0,Australia,Aus,2020,TRUE,44000,99000
15,44,3.0,Australia,Aus,1999,False,88000,101000
16,19,4.5,India,In,1984,False,19000,40000
17,39,5.3,New York,Ny,1943,TRUE,44000,99000
18,35,6.7,New York,Ny,1954,TRUE,44000,99000
19,32,3.3,New York,Ny,1955,TRUE,44000,99000
20,39,5.7,New York,Ny,1944,TRUE,44000,99000
21,35,5.0,New York,Ny,1946,False,44000,99000
22,19,7.8,New York,Ny,1988,TRUE,55000,66000
23,39,2.4,New York,Ny,1999,TRUE,44000,99000
24,13,4.3,New York,Ny,1987,False,44000,99000
25,55,0.0,Australia,Aus,1980,TRUE,44000,99000
26,39,4.3,India,In,1934,TRUE,55000,66000
27,52,5.4,India,In,1935,False,44000,99000
28,39,3.4,Australia,Aus,1932,False,39000,88000

**Second dataset**

In [ ]:
### Second dataset
path='/content/drive/MyDrive/chipotle.tsv'
df=pd.read_csv(path,sep='\t')

In [ ]:
df.isnull().sum()
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
df.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

In [ ]:
df.tail(20)

,order_id,quantity,item_name,choice_description,item_price
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df['item_price']=df.item_price.str.replace("$"," ")
df

<ipython-input-40-568912aa4de8>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['item_price']=df.item_price.str.replace("$"," ")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df['choice_description']=df.choice_description.str.replace("["," ")
df['choice_description']=df.choice_description.str.replace("]"," ")
df['choice_description']= df['choice_description'].replace(np.nan, None)
df.head(10)

<ipython-input-41-ae86b5b386e6>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df.choice_description.str.replace("["," ")
<ipython-input-41-ae86b5b386e6>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df.choice_description.str.replace("]"," ")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,None,2.39
1,1,1,Izze,Clementine,3.39
2,1,1,Nantucket Nectar,Apple,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,2.39
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16.98
5,3,1,Chicken Bowl,"Fresh Tomato Salsa (Mild), Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,None,1.69
7,4,1,Steak Burrito,"Tomatillo Red Chili Salsa, Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"Tomatillo Green Chili Salsa, Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Black Beans, Pinto...",9.25

In [ ]:
df[['choice_0','choice_1','choice_2','choice_3','choice_4','choice_5','choice_6','choice_7','choice_8','choice_9']]=df['choice_description'].str.split("," ,expand=True)
df

,order_id,quantity,item_name,choice_description,item_price,choice_0,choice_1,choice_2,choice_3,choice_4,choice_5,choice_6,choice_7,choice_8,choice_9
0,1,1,Chips and Fresh Tomato Salsa,None,2.39,None,None,None,None,None,None,None,None,None,None
1,1,1,Izze,Clementine,3.39,Clementine,None,None,None,None,None,None,None,None,None
2,1,1,Nantucket Nectar,Apple,3.39,Apple,None,None,None,None,None,None,None,None,None
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,2.39,None,None,None,None,None,None,None,None,None,None
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16.98,Tomatillo-Red Chili Salsa (Hot),Black Beans,Rice,Cheese,Sour Cream,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Black Beans, Sour ...",11.75,Fresh Tomato Salsa,Rice,Black Beans,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None
4618,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Sour Cream, Cheese...",11.75,Fresh Tomato Salsa,Rice,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,None
4619,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",11.25,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Guacamole,Lettuce,None,None,None,None,None
4620,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Lettu...",8.75,Fresh Tomato Salsa,Fajita Vegetables,Lettuce,None,None,None,None,None,None,None
4621,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",8.75,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Lettuce,None,None,None,None,None,None

In [ ]:
new_columns=['order_id','quantity','item_name','choice_description','choice_0','choice_2','choice_3','choice_4','choice_5','choice_6','choice_7','choice_8','choice_9']
df=df[new_columns]
df

,order_id,quantity,item_name,choice_description,choice_0,choice_2,choice_3,choice_4,choice_5,choice_6,choice_7,choice_8,choice_9
0,1,1,Chips and Fresh Tomato Salsa,None,None,None,None,None,None,None,None,None,None
1,1,1,Izze,Clementine,Clementine,None,None,None,None,None,None,None,None
2,1,1,Nantucket Nectar,Apple,Apple,None,None,None,None,None,None,None,None
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,None,None,None,None,None,None,None,None,None
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",Tomatillo-Red Chili Salsa (Hot),Rice,Cheese,Sour Cream,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Black Beans, Sour ...",Fresh Tomato Salsa,Black Beans,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None
4618,1833,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Sour Cream, Cheese...",Fresh Tomato Salsa,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,None
4619,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",Fresh Tomato Salsa,Pinto Beans,Guacamole,Lettuce,None,None,None,None,None
4620,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Lettu...",Fresh Tomato Salsa,Lettuce,None,None,None,None,None,None,None
4621,1834,1,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",Fresh Tomato Salsa,Pinto Beans,Lettuce,None,None,None,None,None,None

In [ ]:
df.head(10)

,order_id,quantity,item_name,choice_description,choice_0,choice_2,choice_3,choice_4,choice_5,choice_6,choice_7,choice_8,choice_9
0,1,1,Chips and Fresh Tomato Salsa,None,None,None,None,None,None,None,None,None,None
1,1,1,Izze,Clementine,Clementine,None,None,None,None,None,None,None,None
2,1,1,Nantucket Nectar,Apple,Apple,None,None,None,None,None,None,None,None
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,None,None,None,None,None,None,None,None,None
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",Tomatillo-Red Chili Salsa (Hot),Rice,Cheese,Sour Cream,None,None,None,None,None
5,3,1,Chicken Bowl,"Fresh Tomato Salsa (Mild), Rice, Cheese, Sou...",Fresh Tomato Salsa (Mild),Cheese,Sour Cream,Guacamole,Lettuce,None,None,None,None
6,3,1,Side of Chips,None,None,None,None,None,None,None,None,None,None
7,4,1,Steak Burrito,"Tomatillo Red Chili Salsa, Fajita Vegetables...",Tomatillo Red Chili Salsa,Black Beans,Pinto Beans,Cheese,Sour Cream,Guacamole,Lettuce,None,None
8,4,1,Steak Soft Tacos,"Tomatillo Green Chili Salsa, Pinto Beans, Ch...",Tomatillo Green Chili Salsa,Cheese,Sour Cream,Lettuce,None,None,None,None,None
9,5,1,Steak Burrito,"Fresh Tomato Salsa, Rice, Black Beans, Pinto...",Fresh Tomato Salsa,Black Beans,Pinto Beans,Cheese,Sour Cream,Lettuce,None,None,None